### PR TITLE
Try to understand how this code works

### PR DESCRIPTION
**Pull request by Jedoku**

### CODE REVIEW

**Review by bodyyyya — COMMENTED** [review]
On my opinion this code created to find out your parent's b-day and understand this b-day will be in this year, month or day, maybe???

**Comment by sanyakosivchuk** [comment]
counts how much days left till ur birthday 🧷

**Comment by sanyakosivchuk** [comment]
also as u said earlier if code isnt understandable at it first look then its trash 😤

**Comment by Jedoku** [comment]
> 



> 

It more than understandable, you will see it later.

**Pull request closed without merging**
