### PR TITLE
capitalize-string

### PR DESCRIPTION
**Pull request by Jedoku**

### CODE REVIEW

**Review by sanyakosivchuk — COMMENTED** [review]
very good no issues with code

**Comment by Jedoku** [comment]
> very good no issues with code

what about attempt to approve?

**Review by Xiollx — APPROVED** [review]

**Review by yawwkee — COMMENTED** [review]
do you like black wet monkeys?

**Review by yaroslav069 — APPROVED** [review]
cocacolastic!

**Review by sanyakosivchuk — APPROVED** [review]

**Pull request merged**
